USE [master]
GO
/****** Object:  Database [ADMIN_NOTAS_DB]    Script Date: 10/4/2024 5:26:31 PM ******/
CREATE DATABASE [ADMIN_NOTAS_DB]
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ADMIN_NOTAS_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET  MULTI_USER 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ADMIN_NOTAS_DB', N'ON'
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET QUERY_STORE = OFF
GO
USE [ADMIN_NOTAS_DB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10/4/2024 5:26:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ETIQUETA]    Script Date: 10/4/2024 5:26:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ETIQUETA](
	[ID_ETIQUETA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
 CONSTRAINT [PK_ETIQUETA] PRIMARY KEY CLUSTERED 
(
	[ID_ETIQUETA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTA]    Script Date: 10/4/2024 5:26:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTA](
	[ID_NOTA] [int] IDENTITY(1,1) NOT NULL,
	[CONTENIDO] [nvarchar](200) NOT NULL,
	[ESTADO] [nvarchar](10) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[FECHA_RECORDATORIO] [datetime] NULL,
	[ID_ETIQUETA] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
 CONSTRAINT [PK_NOTA] PRIMARY KEY CLUSTERED 
(
	[ID_NOTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 10/4/2024 5:26:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[PASS] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_ETIQUETA_ID_USUARIO]    Script Date: 10/4/2024 5:26:31 PM ******/
CREATE NONCLUSTERED INDEX [IX_ETIQUETA_ID_USUARIO] ON [dbo].[ETIQUETA]
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_NOTA_ID_ETIQUETA]    Script Date: 10/4/2024 5:26:31 PM ******/
CREATE NONCLUSTERED INDEX [IX_NOTA_ID_ETIQUETA] ON [dbo].[NOTA]
(
	[ID_ETIQUETA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_NOTA_ID_USUARIO]    Script Date: 10/4/2024 5:26:31 PM ******/
CREATE NONCLUSTERED INDEX [IX_NOTA_ID_USUARIO] ON [dbo].[NOTA]
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_USUARIO_USERNAME]    Script Date: 10/4/2024 5:26:31 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_USUARIO_USERNAME] ON [dbo].[USUARIO]
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ETIQUETA]  WITH CHECK ADD  CONSTRAINT [FK_ETIQUETA_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[ETIQUETA] CHECK CONSTRAINT [FK_ETIQUETA_USUARIO]
GO
ALTER TABLE [dbo].[NOTA]  WITH CHECK ADD  CONSTRAINT [FK_NOTA_ETIQUETA] FOREIGN KEY([ID_ETIQUETA])
REFERENCES [dbo].[ETIQUETA] ([ID_ETIQUETA])
GO
ALTER TABLE [dbo].[NOTA] CHECK CONSTRAINT [FK_NOTA_ETIQUETA]
GO
ALTER TABLE [dbo].[NOTA]  WITH CHECK ADD  CONSTRAINT [FK_NOTA_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[NOTA] CHECK CONSTRAINT [FK_NOTA_USUARIO]
GO
USE [master]
GO
ALTER DATABASE [ADMIN_NOTAS_DB] SET  READ_WRITE 
GO
